#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: September 4th, 2014
# -----------------------------------------------------------------------------


if [ ! -f /data/Tekkit.jar ]
then
    curl "http://mirror.technicpack.net/Technic/servers/tekkitmain/Tekkit_Server_v1.2.9e.zip" > tekkit.zip && \
    unzip tekkit.zip -d /data/
fi


# Run supervisor which maintains the minecraft server
/usr/bin/supervisord

